Refactor the backend for products + adding some methods
Zhelus/fwdx pull request #29
Opened 2024-11-28 05:29 UTC by dangnguyen22

Refactoring the backend for product by adding some methods to help with fetching products.

2024-11-29 20:44 UTC, Zhelus requested changes
Please use a *service.py for your method in mongodb_connector.py
def fetch_all_documents_by_filter(self, filter: dict, collection: CollectionType):

The mongodb_connector.py is designed to be exclusively used to created a connection to the database

2024-11-29 21:18 UTC, Zhelus submitted a review, later dismissed

2024-11-29 23:42 UTC, dangnguyen22 commented
I feel like this method is also a CRUD operations, which is also similar to methods in MongoDBConnector such as     

- def fetch_documents(self, limit: int, collection: CollectionType) and 
- def fetch_document(self, document: dict, collection: CollectionType)
where they are methods to fetch documents using limit and fetch a single document, where as the current method is also to fetch document by using a filter.

2024-12-01 21:08 UTC, Zhelus approved these changes

2024-12-01 21:10 UTC, Zhelus approved these changes

2024-12-01 21:13 UTC, Zhelus approved these changes

2024-12-01 21:13 UTC, merged